-- ePTW Transaction Engine Schema
CREATE TABLE IF NOT EXISTS PTW_Records (
    ptw_id TEXT PRIMARY KEY,
    project_id TEXT NOT NULL,
    ptw_type TEXT DEFAULT 'Work at Height',
    work_description TEXT NOT NULL,
    assigned_workers_json TEXT, 
    selected_rams_json TEXT, 
    status TEXT DEFAULT 'Draft', 
    valid_until DATETIME,
    applicant_signature TEXT,
    safety_signature TEXT,
    pm_signature TEXT,
    safety_vetted_at DATETIME,
    pm_approved_at DATETIME,
    closed_at DATETIME,
    rejection_reason TEXT,
    applicant_email TEXT,
    assigned_wsho_name TEXT,
    assigned_wsho_email TEXT,
    assigned_pm_name TEXT,
    assigned_pm_email TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (project_id) REFERENCES Project_Directory(project_id) ON DELETE CASCADE
);
